### ISSUE TITLE
Provide a solution where MathContext does not need to be passed to all methods

### ISSUE THREAD

**Issue by eobermuhlner** [eobermuhlner/big-math#12]
Copy paste from blog comment:

At the moment, BigDecimalMath requires you to submit a java.math.MathContext
every single time. Is it possible for you to add the option to omit that,
or have the situation so that users might submit or overwrite a MAthContext
once at the beginning, and include only the number parameters for the functions
inside BigDecimalMath?

**Comment by eobermuhlner** [comment]
I agree it is annoying 😉

There would be two possibilities:
1) Have a static setter for a default MathContext.
While this would be fairly simple it is also very ugly because the class beomes statefull (Imagine the race conditions if 2 threads set the MathContext differently).
2) Create a context class where every instance has a MathContext and provides the math functions using this MathContext.
Much better that 1) because the state is in a specific instance.
Also a bit harder to use, because now you need to pass around this context instance (or keep a global instance).
The BigFloat class in the big-math library was an experimental attempt to provide such a context, but I am not sure how good it holds up to reality…
You can easily write this context class yourself for your project.
I will think about it (just added an issue to github https://github.com/eobermuhlner/big-math/issues/12 )
and might add such a context to big-math.

**Comment by eobermuhlner** [comment]
The disadvantage of solution 2) described above is that you do not gain much in the final code.
Instead of
```
y = sin(x, mathContext);
```
you would have to write
```
y = context.sin(x);
```

**Comment by paroxayte** [comment]
I was just creating a branch with a static bin solution similar to what you suggested in solution one. I figure just make a mutable wrapper around an optional value and have it set to throw an error if a method is called without the default being set. Just a suggestion to solve your arms race dilemma perhaps the bin should be designed so that if a default is set, it is effectively final. (Immutable after setting). 
The way I see it the drawback is that if someone requires many different degrees of precision throughout the program, they cannot use the shorthanded methods and must manually specify each time. However for simple applications like the TUI calculator I am currently working on, this may be fine and convenient.

**Comment by eobermuhlner** [comment]
I like the approach with the BigDecimal holding a MathContext.
If you look at the BigFloat class, that is exactly what I tried to do (except that I did not subclass BigDecimal for several reasons).
The disadvantage is that in order to create a constant value you need to pass the MathContext directly or indirectly. It works but it is still cumbersome.

**Comment by paroxayte** [comment]
I actually created such a wrapper although I did not extend it around your library other than pow as my project only needs basic operations. The way it works is you create a DecimalGenerator with a specified MathContext and calling valueOf on a DecimalGenerator creates a RoundedDecimal (wraps around BigDecimal) emeded with said mathContext. https://github.com/paroxayte/PreciseMath

**Comment by IncPlusPlus** [comment]
Hi @eobermuhlner. I was poking around trying to find a good way to have many BigDecimalMath methods without needing to pass a MathContext every time. I ran across Richard J. Mathar's "A Java Math.BigDecimal Implementation of Core Mathematical Functions". Mathar has several functions in [BigDecimalMath.java](https://arxiv.org/src/0908.3030v3/anc/org/nevec/rjm/BigDecimalMath.java) which can be found at [https://arxiv.org/src/0908.3030v3/anc](https://arxiv.org/src/0908.3030v3/anc) which require no MathContext. Unfortunately, I'm not quite experienced enough to understand what his process was to not need a MathContext so I wasn't able to create my own wrapper methods. However, I thought you might be able to figure out how Mathar eliminated the need for a MathContext. I tend use your library instead of his so I look forward to not having to provide a MathContext every time. Best of luck.

**Comment by eobermuhlner** [comment]
Hi @IncPlusPlus 
Thanks for the input.
Yes - using the precision of the `BigDecimal` is a possibility that looks very nice at first glance.

A simple wrapper would look like this:
```java
	public static BigDecimal log(BigDecimal x) {
		MathContext mathContext = new MathContext(x.precision());
		return log(x, mathContext);
	}
```

The problem I see with this solution is that it is incredibly easy to use it completely wrong and get useless results.
The wrapper above would can be used like this:
```java
		System.out.println("BAD log(12.34567) : " + BigDecimalMath.log(BigDecimal.valueOf(12.34567)));
		System.out.println("BAD log(2) : " + BigDecimalMath.log(BigDecimal.valueOf(1)));
```

The output would be:
```
BAD log(12.34567) : 2.513305
BAD log(2) : 0
```
Both results are rounded to the precision of the input argument but this is definitely not the answer you where looking for.

I don't know how Richard J. Mathar is proposing to use his library, but the only approach I found that I can control the precision of a `BigDecimal` value is something like this:
```java
		BigDecimal value = BigDecimal.valueOf(2).setScale(20, RoundingMode.HALF_UP);
		System.out.println("Value : " + value);
		System.out.println("GOOD log(2) : " + BigDecimalMath.log(value));
```
which gives the following output:
```
Value : 2.00000000000000000000
GOOD log(2) : 0.693147180559945309417
```

I believe this usage is *way* too dangerous.
Please tell me if you have found a safe way to use a method like this.

**Comment by eobermuhlner** [comment]
Instead I recommend to write a little wrapper class in your project that provides a hardcoded precision to the wrapped methods:

```java
public static class PrecisionMath {
	private static final MathContext mathContext = new MathContext(100);

	public static BigDecimal log(BigDecimal x) {
		return BigDecimalMath.log(x, mathContext);
	}

	// add more wrapper methods if needed ...
}
```

This class would be specific to your project and cannot be provided by the `big-math` library, because the actual precision hardcoded in it is specific to your needs.

**Comment by eobermuhlner** [comment]
I have found a possible solution where the constant that specifies the default precision is controllable with a system property.

```java
public static class PrecisionMath {
	private static final MathContext mathContext = getSystemMathContext();

	public static BigDecimal log(BigDecimal x) {
		return BigDecimalMath.log(x, mathContext);
	}

	private static MathContext getSystemMathContext () {
		int precision = Integer.parseInt(System.getProperty("ch.obermuhlner.math.big.precision", 100));
		return new MathContext(precision, RoundingMode.HALF_UP);
	}
}
```

If you use `PrecisionMath.log()` without configuring anything then you will have a default precision of 100.
If you need a different precision in your application you set the system property at startup with
```
java -Dch.obermuhlner.math.big.precision=100 MyApplication
```

This guarantees that there are no race conditions and that all usages will see the same precision.

What do you think?

**Comment by IncPlusPlus** [comment]
Hi Eric. Thank you so much for your responses. I really appreciate the amount of effort you put into this project. Your wrapper method idea is what I had been thinking about using but I'm quite intrigued by the idea of setting the precision as a system property. The only problem is that it needs to be done at startup.

This would ordinarily be fine by me but I'm thinking about how I could prompt the user to input the precision. The precision they input can't really take effect because the program has already started.

I think what I'll do is have the user specify the precision to begin with and that value will be assigned to a `final int` and that specific int will be referenced by all operations. I don't think that will cause any problems.

**Comment by eobermuhlner** [comment]
I have decided that I will add a wrapper class `DefaultBigDecimalMath` with a mutable `MathContext`.
It will have setter and getter for the `MathContext`, so the users will be able to set the desired precisions.

A first version of the class is already committed:
https://github.com/eobermuhlner/big-math/blob/master/ch.obermuhlner.math.big/src/main/java/ch/obermuhlner/math/big/DefaultBigDecimalMath.java

I know that this solution has some risks (as discussed above), especially in bigger projects where different parts of the code overwrite each others precision - but in the end this is the responsibility of the users. I will add some javadoc examples to explain good and bad usage of the class.

**Comment by eobermuhlner** [comment]
## Use `DefaultBigDecimalMath` to avoid passing `MathContext`

Due to popular demand a convenience class `DefaultBigDecimalMath` was added that provides mathematical function
where the `MathContext` must not be passed every time.

The class `DefaultBigDecimalMath` is a wrapper around `BigDecimalMath` that passes always the same default `MathContext` to the
functions that need a `MathContext` argument.

This class is designed for applications that will always need the same precision in all calculations.

The initial default `MathContext` is equivalent to `MathContext#DECIMAL128`
but this can be overridden by setting the following system properties:
* `ch.obermuhlner.math.big.default.precision` to a positive integer precision (default=34)
* `ch.obermuhlner.math.big.default.rounding` to a `RoundingMode` name (default=HALF_UP)

It is also possible to set the default `MathContext` using `DefaultBigDecimalMath.setDefaultMathContext(MathContext)`.
It is recommended tp set the desired precision in the `MathContext` early in the startup of the application.

*Important*: Avoid the pitfall of setting the precision temporarily for a calculation.
This can lead to race conditions and calculations with the wrong precision
if other threads in your application do the same thing.
