### ISSUE TITLE
divide by x and multiply by 1/x return different results

### ISSUE THREAD

**Issue by ThDudk** [eobermuhlner/big-math#72]
For some reason, when multiplying by a reciprocal, the result isn't properly rounded.

The code:
System.out.println(DefaultBigDecimalMath.divide(new BigDecimal("2"), new BigDecimal("3")))
System.out.println(DefaultBigDecimalMath.multiply(new BigDecimal("2"), DefaultBigDecimalMath.divide(BigDecimal.ONE, new BigDecimal("3"))));

Result:
0.6666666666666666666666666666666667
0.6666666666666666666666666666666666

**Comment by eobermuhlner** [comment]
Unfortunately this is an inevitable effect of arbitrary precision such as `BigDecimal` and cannot be fixed in the `big-math` library.
Here a simple example that shows the problem.
Calculating 1 / 3 with 5 digits precision gives: 0.33333
Multiply again with 3 and you get: 0.99999
Since you cut of the 0.000003333333333.... after the first calculation.
Calculating in the other order will not be a problem: 1 * 3 / 3 = 1.00000

The only mitigation for this is to calculate with more precision than you want to show and the round to the desired precision at the end of the calculation.
Please note that this gives no guarantee for correctness of the last digit, because it might just be at the border of being rounded up or down.
Calculating with n extra digits gives a statistical risk of 1/10^n of the last digit being wrong (if all digits are equally probable).

If you need perfect accuracy in your calculations you can use the `BigRational` class that represents numbers as rationals.
This will be perfectly accurate if you stick only to basic arithmetic. The price for this is that the internal number representation of `BigRational` can become very big.
